<?xml version="1.0"?>
<!DOCTYPE dump [
  <!ELEMENT dump (component*)>
  <!ELEMENT component (property+, subcomponents?, subwindows?, exception?)>
  <!ELEMENT subcomponents (component+)>
  <!ELEMENT subwindows (component+)>
  <!ELEMENT property EMPTY>
  <!ELEMENT exception EMPTY>
  <!ATTLIST component
            operator CDATA #IMPLIED>
  <!ATTLIST exception
            toString CDATA #REQUIRED>
  <!ATTLIST property
            name  CDATA #REQUIRED
            value CDATA #REQUIRED>
]>
<dump>
  <component operator="org.netbeans.jemmy.operators.JFrameOperator">
    <property name="Class" value="org.gjt.sp.jedit.View"/>
    <property name="Height" value="589"/>
    <property name="Name:" value="frame3"/>
    <property name="Resizable" value="true"/>
    <property name="Showing" value="true"/>
    <property name="State" value="NORMAL"/>
    <property name="Title" value="jEdit - Untitled-1"/>
    <property name="Visible" value="true"/>
    <property name="Width" value="816"/>
    <property name="X" value="858"/>
    <property name="Y" value="300"/>
    <property name="toString" value="org.gjt.sp.jedit.View[active]"/>
    <subcomponents>
      <component operator="org.netbeans.jemmy.operators.JComponentOperator">
        <property name="Class" value="javax.swing.JRootPane"/>
        <property name="Height" value="551"/>
        <property name="Showing" value="true"/>
        <property name="Visible" value="true"/>
        <property name="Width" value="800"/>
        <property name="X" value="8"/>
        <property name="Y" value="30"/>
        <property name="toString" value="javax.swing.JRootPane[,8,30,800x551,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=]"/>
        <subcomponents>
          <component operator="org.netbeans.jemmy.operators.JComponentOperator">
            <property name="Class" value="javax.swing.JPanel"/>
            <property name="Height" value="551"/>
            <property name="Name:" value="null.glassPane"/>
            <property name="Showing" value="false"/>
            <property name="Visible" value="false"/>
            <property name="Width" value="800"/>
            <property name="X" value="0"/>
            <property name="Y" value="0"/>
            <property name="toString" value="javax.swing.JPanel[null.glassPane,0,0,800x551,hidden,layout=java.awt.FlowLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777217,maximumSize=,minimumSize=,preferredSize=]"/>
          </component>
          <component operator="org.netbeans.jemmy.operators.JComponentOperator">
            <property name="Class" value="javax.swing.JLayeredPane"/>
            <property name="Height" value="551"/>
            <property name="Name:" value="null.layeredPane"/>
            <property name="Showing" value="true"/>
            <property name="Visible" value="true"/>
            <property name="Width" value="800"/>
            <property name="X" value="0"/>
            <property name="Y" value="0"/>
            <property name="toString" value="javax.swing.JLayeredPane[null.layeredPane,0,0,800x551,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=,optimizedDrawingPossible=true]"/>
            <subcomponents>
              <component operator="org.netbeans.jemmy.operators.JComponentOperator">
                <property name="Class" value="javax.swing.JPanel"/>
                <property name="Height" value="528"/>
                <property name="Name:" value="null.contentPane"/>
                <property name="Showing" value="true"/>
                <property name="Visible" value="true"/>
                <property name="Width" value="800"/>
                <property name="X" value="0"/>
                <property name="Y" value="23"/>
                <property name="toString" value="javax.swing.JPanel[null.contentPane,0,23,800x528,layout=javax.swing.JRootPane$1,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=]"/>
                <subcomponents>
                  <component operator="org.netbeans.jemmy.operators.JComponentOperator">
                    <property name="Class" value="org.gjt.sp.jedit.gui.DockableWindowManagerImpl"/>
                    <property name="Height" value="504"/>
                    <property name="Showing" value="true"/>
                    <property name="Visible" value="true"/>
                    <property name="Width" value="800"/>
                    <property name="X" value="0"/>
                    <property name="Y" value="0"/>
                    <property name="toString" value="org.gjt.sp.jedit.gui.DockableWindowManagerImpl[,0,0,800x504,layout=org.gjt.sp.jedit.gui.DockableLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=]"/>
                    <subcomponents>
                      <component operator="org.netbeans.jemmy.operators.JComponentOperator">
                        <property name="Class" value="javax.swing.JPanel"/>
                        <property name="Height" value="504"/>
                        <property name="Showing" value="true"/>
                        <property name="Visible" value="true"/>
                        <property name="Width" value="775"/>
                        <property name="X" value="25"/>
                        <property name="Y" value="0"/>
                        <property name="toString" value="javax.swing.JPanel[,25,0,775x504,layout=java.awt.BorderLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=]"/>
                        <subcomponents>
                          <component operator="org.netbeans.jemmy.operators.JComponentOperator">
                            <property name="Class" value="org.gjt.sp.jedit.EditPane"/>
                            <property name="Height" value="468"/>
                            <property name="Showing" value="true"/>
                            <property name="Visible" value="true"/>
                            <property name="Width" value="775"/>
                            <property name="X" value="0"/>
                            <property name="Y" value="36"/>
                            <property name="toString" value="org.gjt.sp.jedit.EditPane[active]"/>
                            <subcomponents>
                              <component operator="org.netbeans.jemmy.operators.JComponentOperator">
                                <property name="Class" value="org.gjt.sp.jedit.textarea.JEditTextArea"/>
                                <property name="Height" value="443"/>
                                <property name="Showing" value="true"/>
                                <property name="Visible" value="true"/>
                                <property name="Width" value="775"/>
                                <property name="X" value="0"/>
                                <property name="Y" value="25"/>
                                <property name="toString" value="org.gjt.sp.jedit.textarea.JEditTextArea[,0,25,775x443,layout=org.gjt.sp.jedit.textarea.ScrollLayout,alignmentX=0.0,alignmentY=0.0,border=org.gjt.sp.jedit.textarea.TextAreaBorder@42bc5245,flags=0,maximumSize=,minimumSize=,preferredSize=,caret=0,caretLine=0,caretScreenLine=-1,electricScroll=3,horizontalOffset=0,magicCaret=0,offsetXY=java.awt.Point[x=0,y=0],oldCaretLine=0,screenLastLine=0,visibleLines=25,firstPhysicalLine=0,physLastLine=0]"/>
                                <subcomponents>
                                  <component operator="org.netbeans.jemmy.operators.JComponentOperator">
                                    <property name="Class" value="org.gjt.sp.jedit.textarea.TextAreaPainter"/>
                                    <property name="Height" value="425"/>
                                    <property name="Showing" value="true"/>
                                    <property name="Visible" value="true"/>
                                    <property name="Width" value="729"/>
                                    <property name="X" value="29"/>
                                    <property name="Y" value="1"/>
                                    <property name="toString" value="org.gjt.sp.jedit.textarea.TextAreaPainter[,29,1,729x425,alignmentX=0.0,alignmentY=0.0,border=,flags=54525960,maximumSize=,minimumSize=,preferredSize=]"/>
                                  </component>
                                  <component operator="org.netbeans.jemmy.operators.JComponentOperator">
                                    <property name="Class" value="org.gjt.sp.jedit.textarea.Gutter"/>
                                    <property name="Height" value="425"/>
                                    <property name="Showing" value="true"/>
                                    <property name="Visible" value="true"/>
                                    <property name="Width" value="28"/>
                                    <property name="X" value="1"/>
                                    <property name="Y" value="1"/>
                                    <property name="toString" value="org.gjt.sp.jedit.textarea.Gutter[,1,1,28x425,alignmentX=0.0,alignmentY=0.0,border=javax.swing.border.CompoundBorder@7aa8198c,flags=54525960,maximumSize=,minimumSize=,preferredSize=]"/>
                                  </component>
                                  <component operator="org.netbeans.jemmy.operators.JComponentOperator">
                                    <property name="Class" value="javax.swing.Box"/>
                                    <property name="Height" value="425"/>
                                    <property name="Showing" value="true"/>
                                    <property name="Visible" value="true"/>
                                    <property name="Width" value="15"/>
                                    <property name="X" value="758"/>
                                    <property name="Y" value="1"/>
                                    <property name="toString" value="javax.swing.Box[,758,1,15x425,layout=javax.swing.BoxLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=]"/>
                                    <subcomponents>
                                      <component operator="org.netbeans.jemmy.operators.JScrollBarOperator">
                                        <property name="Class" value="javax.swing.JScrollBar"/>
                                        <property name="Height" value="425"/>
                                        <property name="Maximum" value="1"/>
                                        <property name="Minimum" value="0"/>
                                        <property name="Orientation" value="VERTICAL"/>
                                        <property name="Showing" value="true"/>
                                        <property name="Value" value="0"/>
                                        <property name="Visible" value="true"/>
                                        <property name="Width" value="15"/>
                                        <property name="X" value="0"/>
                                        <property name="Y" value="0"/>
                                        <property name="toString" value="javax.swing.JScrollBar[,0,0,15x425,layout=javax.swing.plaf.metal.MetalScrollBarUI,alignmentX=0.0,alignmentY=0.0,border=,flags=4194632,maximumSize=,minimumSize=,preferredSize=,blockIncrement=25,orientation=VERTICAL,unitIncrement=2]"/>
                                        <subcomponents>
                                          <component operator="org.netbeans.jemmy.operators.JButtonOperator">
                                            <property name="Class" value="javax.swing.plaf.metal.MetalScrollButton"/>
                                            <property name="Default button" value="false"/>
                                            <property name="Height" value="15"/>
                                            <property name="Showing" value="true"/>
                                            <property name="Text" value=""/>
                                            <property name="Visible" value="true"/>
                                            <property name="Width" value="15"/>
                                            <property name="X" value="0"/>
                                            <property name="Y" value="410"/>
                                            <property name="toString" value="javax.swing.plaf.metal.MetalScrollButton[,0,410,15x15,alignmentX=0.0,alignmentY=0.5,border=javax.swing.plaf.BorderUIResource$CompoundBorderUIResource@1acfb11f,flags=4194600,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,disabledSelectedIcon=,margin=javax.swing.plaf.InsetsUIResource[top=2,left=14,bottom=2,right=14],paintBorder=true,paintFocus=true,pressedIcon=,rolloverEnabled=true,rolloverIcon=,rolloverSelectedIcon=,selectedIcon=,text=,defaultCapable=true]"/>
                                          </component>
                                          <component operator="org.netbeans.jemmy.operators.JButtonOperator">
                                            <property name="Class" value="javax.swing.plaf.metal.MetalScrollButton"/>
                                            <property name="Default button" value="false"/>
                                            <property name="Height" value="15"/>
                                            <property name="Showing" value="true"/>
                                            <property name="Text" value=""/>
                                            <property name="Visible" value="true"/>
                                            <property name="Width" value="15"/>
                                            <property name="X" value="0"/>
                                            <property name="Y" value="0"/>
                                            <property name="toString" value="javax.swing.plaf.metal.MetalScrollButton[,0,0,15x15,alignmentX=0.0,alignmentY=0.5,border=javax.swing.plaf.BorderUIResource$CompoundBorderUIResource@1acfb11f,flags=4194600,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,disabledSelectedIcon=,margin=javax.swing.plaf.InsetsUIResource[top=2,left=14,bottom=2,right=14],paintBorder=true,paintFocus=true,pressedIcon=,rolloverEnabled=true,rolloverIcon=,rolloverSelectedIcon=,selectedIcon=,text=,defaultCapable=true]"/>
                                          </component>
                                        </subcomponents>
                                      </component>
                                    </subcomponents>
                                  </component>
                                  <component operator="org.netbeans.jemmy.operators.JScrollBarOperator">
                                    <property name="Class" value="javax.swing.JScrollBar"/>
                                    <property name="Height" value="15"/>
                                    <property name="Maximum" value="0"/>
                                    <property name="Minimum" value="0"/>
                                    <property name="Orientation" value="HORIZONTAL"/>
                                    <property name="Showing" value="true"/>
                                    <property name="Value" value="0"/>
                                    <property name="Visible" value="true"/>
                                    <property name="Width" value="757"/>
                                    <property name="X" value="1"/>
                                    <property name="Y" value="426"/>
                                    <property name="toString" value="javax.swing.JScrollBar[,1,426,757x15,layout=javax.swing.plaf.metal.MetalScrollBarUI,alignmentX=0.0,alignmentY=0.0,border=,flags=4194632,maximumSize=,minimumSize=,preferredSize=,blockIncrement=10,orientation=HORIZONTAL,unitIncrement=1]"/>
                                    <subcomponents>
                                      <component operator="org.netbeans.jemmy.operators.JButtonOperator">
                                        <property name="Class" value="javax.swing.plaf.metal.MetalScrollButton"/>
                                        <property name="Default button" value="false"/>
                                        <property name="Height" value="15"/>
                                        <property name="Showing" value="true"/>
                                        <property name="Text" value=""/>
                                        <property name="Visible" value="true"/>
                                        <property name="Width" value="15"/>
                                        <property name="X" value="742"/>
                                        <property name="Y" value="0"/>
                                        <property name="toString" value="javax.swing.plaf.metal.MetalScrollButton[,742,0,15x15,alignmentX=0.0,alignmentY=0.5,border=javax.swing.plaf.BorderUIResource$CompoundBorderUIResource@1acfb11f,flags=4194600,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,disabledSelectedIcon=,margin=javax.swing.plaf.InsetsUIResource[top=2,left=14,bottom=2,right=14],paintBorder=true,paintFocus=true,pressedIcon=,rolloverEnabled=true,rolloverIcon=,rolloverSelectedIcon=,selectedIcon=,text=,defaultCapable=true]"/>
                                      </component>
                                      <component operator="org.netbeans.jemmy.operators.JButtonOperator">
                                        <property name="Class" value="javax.swing.plaf.metal.MetalScrollButton"/>
                                        <property name="Default button" value="false"/>
                                        <property name="Height" value="15"/>
                                        <property name="Showing" value="true"/>
                                        <property name="Text" value=""/>
                                        <property name="Visible" value="true"/>
                                        <property name="Width" value="15"/>
                                        <property name="X" value="0"/>
                                        <property name="Y" value="0"/>
                                        <property name="toString" value="javax.swing.plaf.metal.MetalScrollButton[,0,0,15x15,alignmentX=0.0,alignmentY=0.5,border=javax.swing.plaf.BorderUIResource$CompoundBorderUIResource@1acfb11f,flags=4194600,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,disabledSelectedIcon=,margin=javax.swing.plaf.InsetsUIResource[top=2,left=14,bottom=2,right=14],paintBorder=true,paintFocus=true,pressedIcon=,rolloverEnabled=true,rolloverIcon=,rolloverSelectedIcon=,selectedIcon=,text=,defaultCapable=true]"/>
                                      </component>
                                    </subcomponents>
                                  </component>
                                </subcomponents>
                              </component>
                              <component operator="org.netbeans.jemmy.operators.JComboBoxOperator">
                                <property name="Class" value="org.gjt.sp.jedit.gui.BufferSwitcher"/>
                                <property name="Height" value="25"/>
                                <property name="Item_0" value="Untitled-1 (%USERPROFILE%\)"/>
                                <property name="Showing" value="true"/>
                                <property name="Text" value="Untitled-1 (%USERPROFILE%\)"/>
                                <property name="Tooltip text" value="%USERPROFILE%\Untitled-1"/>
                                <property name="Visible" value="true"/>
                                <property name="Width" value="775"/>
                                <property name="X" value="0"/>
                                <property name="Y" value="0"/>
                                <property name="toString" value="org.gjt.sp.jedit.gui.BufferSwitcher[,0,0,775x25,layout=javax.swing.plaf.metal.MetalComboBoxUI$MetalComboBoxLayoutManager,alignmentX=0.0,alignmentY=0.0,border=,flags=328,maximumSize=,minimumSize=,preferredSize=,isEditable=false,lightWeightPopupEnabled=true,maximumRowCount=10,selectedItemReminder=Untitled-1 (%USERPROFILE%\)]"/>
                                <subcomponents>
                                  <component operator="org.netbeans.jemmy.operators.JButtonOperator">
                                    <property name="Class" value="javax.swing.plaf.metal.MetalComboBoxButton"/>
                                    <property name="Default button" value="false"/>
                                    <property name="Height" value="25"/>
                                    <property name="Showing" value="true"/>
                                    <property name="Text" value=""/>
                                    <property name="Tooltip text" value="%USERPROFILE%\Untitled-1"/>
                                    <property name="Visible" value="true"/>
                                    <property name="Width" value="20"/>
                                    <property name="X" value="755"/>
                                    <property name="Y" value="0"/>
                                    <property name="toString" value="javax.swing.plaf.metal.MetalComboBoxButton[,755,0,20x25,alignmentX=0.0,alignmentY=0.5,border=javax.swing.plaf.BorderUIResource$CompoundBorderUIResource@1acfb11f,flags=12583208,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,disabledSelectedIcon=,margin=java.awt.Insets[top=0,left=1,bottom=1,right=3],paintBorder=true,paintFocus=false,pressedIcon=,rolloverEnabled=true,rolloverIcon=,rolloverSelectedIcon=,selectedIcon=,text=,defaultCapable=true]"/>
                                  </component>
                                  <component operator="org.netbeans.jemmy.operators.ContainerOperator">
                                    <property name="Class" value="javax.swing.CellRendererPane"/>
                                    <property name="Height" value="0"/>
                                    <property name="Showing" value="false"/>
                                    <property name="Visible" value="false"/>
                                    <property name="Width" value="0"/>
                                    <property name="X" value="0"/>
                                    <property name="Y" value="0"/>
                                    <property name="toString" value="javax.swing.CellRendererPane[,0,0,0x0,hidden]"/>
                                    <subcomponents>
                                      <component operator="org.netbeans.jemmy.operators.JLabelOperator">
                                        <property name="Class" value="org.gjt.sp.jedit.gui.BufferSwitcher$BufferCellRenderer"/>
                                        <property name="Height" value="0"/>
                                        <property name="Name:" value="List.cellRenderer"/>
                                        <property name="Showing" value="false"/>
                                        <property name="Text" value="Untitled-1 (%USERPROFILE%\)"/>
                                        <property name="Tooltip text" value="C:\Users\Dmitry\Untitled-1"/>
                                        <property name="Visible" value="true"/>
                                        <property name="Width" value="0"/>
                                        <property name="X" value="-752"/>
                                        <property name="Y" value="-18"/>
                                        <property name="toString" value="org.gjt.sp.jedit.gui.BufferSwitcher$BufferCellRenderer[List.cellRenderer,-752,-18,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=javax.swing.border.EmptyBorder@48c4fedd,flags=25165832,maximumSize=,minimumSize=,preferredSize=,defaultIcon=jeditresource:/org/gjt/sp/jedit/icons/themes/tango/10x10/status/document-new.png,disabledIcon=,horizontalAlignment=LEADING,horizontalTextPosition=TRAILING,iconTextGap=4,labelFor=,text=Untitled-1 (%USERPROFILE%\),verticalAlignment=CENTER,verticalTextPosition=CENTER]"/>
                                      </component>
                                    </subcomponents>
                                  </component>
                                </subcomponents>
                              </component>
                            </subcomponents>
                          </component>
                          <component operator="org.netbeans.jemmy.operators.JComponentOperator">
                            <property name="Class" value="javax.swing.JPanel"/>
                            <property name="Height" value="36"/>
                            <property name="Showing" value="true"/>
                            <property name="Visible" value="true"/>
                            <property name="Width" value="775"/>
                            <property name="X" value="0"/>
                            <property name="Y" value="0"/>
                            <property name="toString" value="javax.swing.JPanel[,0,0,775x36,layout=org.gjt.sp.jedit.gui.VariableGridLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=]"/>
                            <subcomponents>
                              <component operator="org.netbeans.jemmy.operators.JComponentOperator">
                                <property name="Class" value="javax.swing.JToolBar"/>
                                <property name="Height" value="36"/>
                                <property name="Name:" value="view.toolbar"/>
                                <property name="Showing" value="true"/>
                                <property name="Visible" value="true"/>
                                <property name="Width" value="775"/>
                                <property name="X" value="0"/>
                                <property name="Y" value="0"/>
                                <property name="toString" value="javax.swing.JToolBar[view.toolbar,0,0,775x36,layout=java.awt.FlowLayout,alignmentX=0.0,alignmentY=0.0,border=javax.swing.plaf.metal.MetalBorders$ToolBarBorder@9826ac5,flags=328,maximumSize=,minimumSize=,preferredSize=,floatable=false,margin=,orientation=HORIZONTAL,paintBorder=true]"/>
                                <subcomponents>
                                  <component operator="org.netbeans.jemmy.operators.JButtonOperator">
                                    <property name="Class" value="org.gjt.sp.jedit.gui.EnhancedButton"/>
                                    <property name="Default button" value="false"/>
                                    <property name="Height" value="32"/>
                                    <property name="Name:" value="new-file"/>
                                    <property name="Showing" value="true"/>
                                    <property name="Text" value=""/>
                                    <property name="Tooltip text" value="New (C+n)"/>
                                    <property name="Visible" value="true"/>
                                    <property name="Width" value="32"/>
                                    <property name="X" value="2"/>
                                    <property name="Y" value="1"/>
                                    <property name="toString" value="org.gjt.sp.jedit.gui.EnhancedButton[new-file,2,1,32x32,alignmentX=0.0,alignmentY=0.5,border=javax.swing.border.CompoundBorder@694b525c,flags=20971808,maximumSize=,minimumSize=,preferredSize=java.awt.Dimension[width=32,height=32],defaultIcon=jeditresource:/org/gjt/sp/jedit/icons/themes/tango/22x22/actions/document-new.png,disabledIcon=,disabledSelectedIcon=,margin=java.awt.Insets[top=1,left=1,bottom=1,right=1],paintBorder=false,paintFocus=true,pressedIcon=,rolloverEnabled=true,rolloverIcon=,rolloverSelectedIcon=,selectedIcon=,text=,defaultCapable=false]"/>
                                  </component>
                                  <component operator="org.netbeans.jemmy.operators.JButtonOperator">
                                    <property name="Class" value="org.gjt.sp.jedit.gui.EnhancedButton"/>
                                    <property name="Default button" value="false"/>
                                    <property name="Height" value="32"/>
                                    <property name="Name:" value="open-file"/>
                                    <property name="Showing" value="true"/>
                                    <property name="Text" value=""/>
                                    <property name="Tooltip text" value="Open... (C+o)"/>
                                    <property name="Visible" value="true"/>
                                    <property name="Width" value="32"/>
                                    <property name="X" value="34"/>
                                    <property name="Y" value="1"/>
                                    <property name="toString" value="org.gjt.sp.jedit.gui.EnhancedButton[open-file,34,1,32x32,alignmentX=0.0,alignmentY=0.5,border=javax.swing.border.CompoundBorder@694b525c,flags=20971808,maximumSize=,minimumSize=,preferredSize=java.awt.Dimension[width=32,height=32],defaultIcon=jeditresource:/org/gjt/sp/jedit/icons/themes/tango/22x22/actions/document-open.png,disabledIcon=,disabledSelectedIcon=,margin=java.awt.Insets[top=1,left=1,bottom=1,right=1],paintBorder=false,paintFocus=true,pressedIcon=,rolloverEnabled=true,rolloverIcon=,rolloverSelectedIcon=,selectedIcon=,text=,defaultCapable=false]"/>
                                  </component>